from pact import Verifier

def test_provider_verification():
    """
    Provider test to verify the provider against the pact file.
    """
    verifier = Verifier(provider='UserService', provider_base_url='https://reqres.in')

    # Enable logging to stdout to capture the actual responses during verification
    verifier.log_dir = "./pact_logs"
    verifier.verbose = True

    # Verify the pact file generated by the consumer
    output, logs = verifier.verify_pacts('./pacts/userclient-userservice.json')

    # Print the logs for debugging and capturing the actual responses
    print("Verification Logs:")
    print(logs)

    # Ensure the verification is successful
    assert output == 0, f"Provider verification failed! Logs: {logs}"